[mgr]
prepend_keymap = [
  { on = [ "<C-s>" ], run = "plugin kdeconnect-send", desc = "Send via KDE Connect" },
  { on = [ "<C-w>" ], run = 'shell --orphan "bash -c \"pkill swaybg; swaybg -i %s -m fill\""' },
]
