exec-once = kdeconnect-indicator
exec-once = mako
exec-once = kitty
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-paste --type text --watch cliphist store
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = swaybg -i ~/Wallpapers/wp12329531-nixos-wallpapers.png -m fill & # bash $HOME/.config/Scripts/random_wall_on_home.sh
exec-once = waybar -c ~/.config/waybar/GlassFlow/config.jsonc -s ~/.config/waybar/GlassFlow/style.css
exec-once = swayidle -w timeout 120 'systemctl suspend' before-sleep 'hyprlock'
