decoration {
    rounding = 24
    rounding_power = 2
    active_opacity = 1.0
    inactive_opacity = 1.0
    blur {
        enabled = true
        size = 8
        passes = 4
        xray = false
        contrast = 1.6
        noise = 0.02
        brightness = 1.0
        vibrancy = 0.4
        vibrancy_darkness = 0.4
        ignore_opacity = true
        new_optimizations = true
    }

    shadow {
      enabled = false
    }
}

