general {
    gaps_in = 5
    gaps_out = 10
    border_size = 4

    #col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = none #rgba(255,255,255,0.6)
    col.active_border = rgba(250,250,250,1.0)

    resize_on_border = true
    layout = scrolling # dwindle
}
