input {
    kb_layout = us
    # kb_variant = dvorak
    repeat_rate = 60
    repeat_delay = 300

    follow_mouse = 1
    accel_profile = adaptive
    scroll_factor = 2.0
    sensitivity = 1.0
    touchpad {
        natural_scroll = true
        tap-and-drag = true
        scroll_factor = 2.0
    }
}

